 URL : "https://github.com/autokey-py3/autokey/issues/115" TITLE : x protocol error: BODY : classification: bug reproducibility: always summary this think is almost impossible to work! steps to reproduce i installed it with pip. it didn't work. i installed it with ppa. it didn't work. it just showed the autokey and autokey kde logos in my applications but when i clicked on them. nth happened. i downloaded the old autokey from googlecodes and tried to build that. which didn't work either. i tried with python setup.py install. didn't work. finally after a few days it just started to work by itself. not that it worked! but at least it could show the gui! but it wasn't functioning correctly at all. it couldn't save the phrases and nth. so today i did locate autokey and removed all the files i could find. then tried to isntall with pip. didn't work. then tried sudo apt install autokey-gtk. and could finally do something after manually installing dbus etc. now when i issue sudo autokey-gtk i get: x protocol error: <class 'xlib.error.badaccess'>: code = 10, resource_id = 260, sequence_number = 15, major_opcode = 33, minor_opcode = 0 x protocol error: <class 'xlib.error.badaccess'>: code = 10, resource_id = 260, sequence_number = 16, major_opcode = 33, minor_opcode = 0 x protocol error: <class 'xlib.error.badaccess'>: code = 10, resource_id = 260, sequence_number = 17, major_opcode = 33, minor_opcode = 0 x protocol error: <class 'xlib.error.badaccess'>: code = 10, resource_id = 260, sequence_number = 18, major_opcode = 33, minor_opcode = 0 i have never tried to install a package and fail as much as i've failed with this! distro: ubuntu 16.04