 URL : "https://github.com/futapi/fut/issues/347" TITLE : keyerror in core.py BODY : file /users/bnwlkr/pycharmprojects/contracts/quickseller.py , line 6, in <module> items = session.clubconsumables file /users/bnwlkr/pycharmprojects/fut/fut/core.py , line 1013, in clubconsumables return {itemparse i for i in rc.get 'itemdata', } file /users/bnwlkr/pycharmprojects/fut/fut/core.py , line 1013, in <setcomp> return {itemparse i for i in rc.get 'itemdata', } file /users/bnwlkr/pycharmprojects/fut/fut/core.py , line 92, in itemparse 'timestamp': item_data 'itemdata' .get 'timestamp' , auction start keyerror: 'itemdata' i am getting this error when i call: 'session.clubconsumables '