 URL : "https://github.com/nltk/nltk_book/issues/189" TITLE : chapter 6 example 2.3 BODY : in chapter 6, example 2.3 lists the following: example 2.3: recognizing textual entailment python >>> rtepair = nltk.corpus.rte.pairs 'rte3_dev.xml' 33 >>> extractor = nltk.rtefeatureextractor rtepair >>> print extractor.text_words {'russia', 'organisation', 'shanghai', 'asia', 'four', 'at', 'operation', 'sco', ...} >>> print extractor.hyp_words {'member', 'sco', 'china'} however, when these lines are run in python the following output is returned: python 3.6 python >>> import nltk >>> rtepair = nltk.corpus.rte.pairs 'rte3_dev.xml' 33 >>> extractor = nltk.rtefeatureextractor rtepair >>> print extractor.text_words {'n', 'z', 'o', 'f', 't', 'g', 's', 'r', 'l', 'e', 'o', 'd', 'i'} >>> print extractor.hyp_words {'f', 's', 'r'} python 2.7 python >>> import nltk >>> rtepair = nltk.corpus.rte.pairs 'rte3_dev.xml' 33 >>> extractor = nltk.rtefeatureextractor rtepair >>> print extractor.text_words set '' >>> print extractor.hyp_words set '' i am unsure if this is simple user error on my end, or if something has changed with nltk that is interfering with this example. any thoughts are appreciated.