 URL : "https://github.com/cevoaustralia/aws-google-auth/issues/14" TITLE : --help broken in 0.0.8 BODY : minor grumble, just installed the 0.0.8 release with pip3 and running aws-google-auth --help breaks with: $ aws-google-auth --help traceback most recent call last : file /usr/local/bin/aws-google-auth , line 11, in <module> load_entry_point 'aws-google-auth==0.0.8', 'console_scripts', 'aws-google-auth' file /usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py , line 561, in load_entry_point return get_distribution dist .load_entry_point group, name file /usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py , line 2631, in load_entry_point return ep.load file /usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py , line 2291, in load return self.resolve file /usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py , line 2297, in resolve module = __import__ self.module_name, fromlist= '__name__' , level=0 file /usr/local/lib/python3.6/site-packages/aws_google_auth/__init__.py , line 55 print warning: clamping duration_seconds to 3600 ^ syntaxerror: missing parentheses in call to 'print'