 URL : "https://github.com/strongloop/loopback-connector-swagger/issues/45" TITLE : test failure on master BODY : 6 tests are failing on current master 37 passing 2s 1 pending 6 failing 1 swagger connector models models without remotingenabled supports model methods: error: done invoked with non-error: { url : http://petstore.swagger.io/v2/pet/1 , method : get , headers :{ date : tue, 22 aug 2017 23:01:49 gmt , access-control-allow-origin : , access-control-allow-methods : get, post, delete, put , access-control-allow-headers : content-type, api_key, authorization , content-type : application/json , connection : close , server : jetty 9.2.9.v20150224 }, errobj :{ original :null, response :{ req :{ method : get , url : http://petstore.swagger.io/v2/pet/1 , headers :{ user-agent : loopback-connector-swagger/3.2.0 , accept : application/json }}, header :{ date : tue, 22 aug 2017 23:01:49 gmt , access-control-allow-origin : , access-control-allow-methods : get, post, delete, put , access-control-allow-headers : content-type, api_key, authorization , content-type : application/json , connection : close , server : jetty 9.2.9.v20150224 }, status :404, text : {\ code\ :1,\ type\ :\ error\ ,\ message\ :\ pet not found\ } }, status :404}, status :404, statustext : {\ code\ :1,\ type\ :\ error\ ,\ message\ :\ pet not found\ } , obj :{ code :1, type : error , message : pet not found }, data : {\ code\ :1,\ type\ :\ error\ ,\ message\ :\ pet not found\ } } at test/test-connector.js:99:27 at failure lib/swagger-connector.js:290:9