 URL : "https://github.com/matthewmueller/vo/issues/12" TITLE : bug in debug mode!!!!!! BODY : my test code: const vo = require 'vo' ; function go { try { console.log 1 ; throw new error 'rrrr' ; return true; } catch error { throw error; } finally { console.log 'finally' } } vo go .then r => { console.log 'then: ', r ; } .catch e => { console.error catch: , e ; } ; no debug mode: node test 1 finally catch: error: rrrr at go c: ode.data\posters\poster\test.js:5:15 at go.next <anonymous> at next c: ode.data\posters\poster ode_modules\co\index.js:74:21 at c: ode.data\posters\poster ode_modules\co\index.js:45:5 at wrap c: ode.data\posters\poster ode_modules\vo\lib\wrap.js:30:21 at func c: ode.data\posters\poster ode_modules\vo\lib\compile.js:44:23 at next c: ode.data\posters\poster ode_modules\vo\lib\pipeline.js:34:15 at pipeline c: ode.data\posters\poster ode_modules\vo\lib\pipeline.js:47:8 at c: ode.data\posters\poster ode_modules\vo\index.js:44:5 at c: ode.data\posters\poster ode_modules\vo\index.js:101:9 in debug mode: >set debug= ,-not_this >node test.js vo â†— go +0ms 1 finaly c: ode.data\posters\poster ode_modules\vo\lib\wrap.js:120 if str.length > limit { ^ typeerror: cannot read property 'length' of undefined at trim c: ode.data\posters\poster ode_modules\vo\lib\wrap.js:120:12 at c: ode.data\posters\poster ode_modules\vo\lib\wrap.js:109:14 at array.map native at pretty c: ode.data\posters\poster ode_modules\vo\lib\wrap.js:108:30 at next c: ode.data\posters\poster ode_modules\vo\lib\wrap.js:36:30 at immediate.<anonymous> c: ode.data\posters\poster ode_modules\co\index.js:52:14 at runcallback timers.js:651:20 at tryonimmediate timers.js:624:5 at processimmediate as _immediatecallback timers.js:596:5