 URL : "https://github.com/ricmoo/pyaes/issues/16" TITLE : python 3 compatibility? BODY : hello. i tried pyaes , but it doesn't work on python 3.3. my code for python 3.3 is: import pyaes any mode of operation can be used; for this example ctr key = this_key_for_demo_purposes_only! create the mode of operation to encrypt with mode = pyaes.aesmodeofoperationctr key.encode the input and output files file_in = open 'c:/temp/7202969_hd.mp4' file_out = open 'c:/temp/7202969_hd.mp4.crypted', 'wb' encrypt the data as a stream, the file is read in 8kb chunks, be default pyaes.encrypt_stream mode, file_in, file_out close the files file_in.close file_out.close this code fails: d:\python33>python.exe cr.py traceback most recent call last : file cr.py , line 55, in <module> pyaes.encrypt_stream mode, file_in, file_out file d:\python33\lib\site-packages\pyaes\blockfeeder.py , line 220, in encrypt_stream _feed_stream encrypter, in_stream, out_stream, block_size file d:\python33\lib\site-packages\pyaes\blockfeeder.py , line 210, in _feed_stream converted = feeder.feed chunk file d:\python33\lib\site-packages\pyaes\blockfeeder.py , line 173, in feed self._buffer += to_bufferable data file d:\python33\lib\site-packages\pyaes\util.py , line 42, in to_bufferable return bytes ord b for b in binary valueerror: bytes must be in range 0, 256 how could it be hot-fixed for python 3.3? thank you!