 URL : "https://github.com/aranega/pyecore/issues/10" TITLE : unexpected proxy object BODY : while implementing the python generator i am loading the library model from examples as sample model. for some reason i get a proxy object for the eint type. i don't understand why... this code reproduces the error, shown here as the failing assertion in the end: python def test__load_issue : rset = resourceset resource = rset.get_resource uri '../../examples/library.ecore' library_model = resource.contents 0 rset.metamodel_registry library_model.nsuri = library_model book_class = library_model.geteclassifier 'book' pages_feature = book_class.findestructuralfeature 'pages' assert not isinstance pages_feature.etype, eproxy am i missing something during the load of the model? thanks!