 URL : "https://github.com/deepmind/lab/issues/61" TITLE : hitting static tls limit BODY : i have successfully managed build lab and run the tests. but, when i try to run more involved code namely unreal https://github.com/miyosuda/unreal , i am getting an error: failed to open library! - ./libdmlab.so dlopen: cannot load any more object with static tls process process-1: traceback most recent call last : file /part/01/tmp/lisa/os_v5/anaconda/lib/python2.7/multiprocessing/process.py , line 258, in _bootstrap self.run file /part/01/tmp/lisa/os_v5/anaconda/lib/python2.7/multiprocessing/process.py , line 114, in run self._target self._args, self._kwargs file /data/lisa/exp/sygnowsj/lab/unreal/environment/lab_environment.py , line 26, in worker 'height': str 84 runtimeerror: failed to connect rl api when creating the environment. i am not an os guru, but as far as i understand it is connected with the way shared libraries are linked within lab. i wonder -- is it possible to force lab to use dynamic tls for some libraries? if not, can i resolve the problem in another way? unfortunately i cannot upgrade glibc to a version with higher dtv_surplus my version is debian glibc 2.19-18+deb8u7 . thank you :