 URL : "https://github.com/annapasca/neuropype/issues/1" TITLE : no module named externals BODY : i am using the nipype 0.12 package and i got this error 170516-16:10:38,459 workflow error: 'node preproc.a0 failed to run on host mint.' 170516-16:10:38,459 workflow info: saving crash info to /home/boukhdha/neuropype_workshop/source_code/crash-20170516-161038-boukhdha-preproc.a0-7a2fc572-24a0-4f34-a8fa-c3b9e6b2c35b.pklz 170516-16:10:38,459 workflow info: traceback most recent call last : file /usr/local/lib/python2.7/dist-packages/nipype/pipeline/plugins/linear.py , line 39, in run node.run updatehash=updatehash file /usr/local/lib/python2.7/dist-packages/nipype/pipeline/engine/nodes.py , line 394, in run self._run_interface file /usr/local/lib/python2.7/dist-packages/nipype/pipeline/engine/nodes.py , line 504, in _run_interface self._result = self._run_command execute file /usr/local/lib/python2.7/dist-packages/nipype/pipeline/engine/nodes.py , line 630, in _run_command result = self._interface.run file /usr/local/lib/python2.7/dist-packages/nipype/interfaces/base.py , line 1034, in run runtime = self._run_wrapper runtime file /usr/local/lib/python2.7/dist-packages/nipype/interfaces/base.py , line 991, in _run_wrapper runtime = self._run_interface runtime file /usr/local/lib/python2.7/dist-packages/nipype/interfaces/utility.py , line 496, in _run_interface raise out importerror: no module named externals interface function failed to run.